-- Baseline schema for the E2E TEST database.
-- Generated by scripts/clone-schema.mjs from the live schema.
-- Do NOT edit by hand; regenerate with:
--   GENERATE_ONLY=1 OUTPUT_FILE=supabase\test-baseline.sql SOURCE_REF=<ref> node scripts/clone-schema.mjs

-- drop order_items
DROP TABLE IF EXISTS public."order_items" CASCADE;

-- drop orders
DROP TABLE IF EXISTS public."orders" CASCADE;

-- drop product_variants
DROP TABLE IF EXISTS public."product_variants" CASCADE;

-- drop product_images
DROP TABLE IF EXISTS public."product_images" CASCADE;

-- drop product_categories
DROP TABLE IF EXISTS public."product_categories" CASCADE;

-- drop products
DROP TABLE IF EXISTS public."products" CASCADE;

-- drop categories
DROP TABLE IF EXISTS public."categories" CASCADE;

-- drop content_versions
DROP TABLE IF EXISTS public."content_versions" CASCADE;

-- drop content_pages
DROP TABLE IF EXISTS public."content_pages" CASCADE;

-- drop company_settings
DROP TABLE IF EXISTS public."company_settings" CASCADE;

-- drop email_templates
DROP TABLE IF EXISTS public."email_templates" CASCADE;

-- drop bookings
DROP TABLE IF EXISTS public."bookings" CASCADE;

-- drop time_slots
DROP TABLE IF EXISTS public."time_slots" CASCADE;

-- drop blocked_dates
DROP TABLE IF EXISTS public."blocked_dates" CASCADE;

-- type bestell_status
DROP TYPE IF EXISTS public."bestell_status" CASCADE; CREATE TYPE public."bestell_status" AS ENUM ('offen', 'bezahlt', 'versandt', 'abgeschlossen', 'storniert', 'erstattet', 'warten_auf_zahlung', 'fehlgeschlagen');

-- type buchung_status
DROP TYPE IF EXISTS public."buchung_status" CASCADE; CREATE TYPE public."buchung_status" AS ENUM ('ausstehend', 'bestaetigt', 'abgeschlossen', 'abgesagt', 'nicht_erschienen');

-- type rolle_typ
DROP TYPE IF EXISTS public."rolle_typ" CASCADE; CREATE TYPE public."rolle_typ" AS ENUM ('kunde', 'admin', 'mitarbeiter');

-- type zahlungs_status
DROP TYPE IF EXISTS public."zahlungs_status" CASCADE; CREATE TYPE public."zahlungs_status" AS ENUM ('initiiert', 'autorisiert', 'erfasst', 'fehlgeschlagen', 'erstattet');

-- type zahlungsanbieter
DROP TYPE IF EXISTS public."zahlungsanbieter" CASCADE; CREATE TYPE public."zahlungsanbieter" AS ENUM ('stripe');

-- table admin_audit_logs
CREATE TABLE IF NOT EXISTS public."admin_audit_logs" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "actor_benutzer_id" uuid,
  "aktion" text NOT NULL,
  "entitaet_typ" text NOT NULL,
  "entitaet_id" uuid,
  "vorher" jsonb,
  "nachher" jsonb,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "admin_id" uuid,
  "details" jsonb
);

-- table artikel
CREATE TABLE IF NOT EXISTS public."artikel" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "artikelnummer" text NOT NULL,
  "titel" text NOT NULL,
  "beschreibung" text,
  "marke_id" uuid,
  "kategorie_id" uuid,
  "preis_brutto" numeric(10,2) NOT NULL,
  "steuersatz" numeric(4,2) DEFAULT 19.00 NOT NULL,
  "installation_option_verfügbar" boolean DEFAULT true NOT NULL,
  "aktiv" boolean DEFAULT true NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL,
  "slug" text,
  "rabattpreis" numeric(10,2),
  "meta_titel" text,
  "meta_beschreibung" text,
  "meta_tags" text[],
  "ist_ab_preis" boolean DEFAULT false NOT NULL,
  "varianten" jsonb DEFAULT '[]'::jsonb NOT NULL
);

-- table artikel_bilder
CREATE TABLE IF NOT EXISTS public."artikel_bilder" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "artikel_id" uuid NOT NULL,
  "datei_id" uuid,
  "alt_text" text,
  "anzeige_reihenfolge" integer DEFAULT 0,
  "erstellt_am" timestamp with time zone DEFAULT now()
);

-- table artikel_technische_daten
CREATE TABLE IF NOT EXISTS public."artikel_technische_daten" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "artikel_id" uuid NOT NULL,
  "anzeige_reihenfolge" integer DEFAULT 0,
  "inhalt" text
);

-- table benutzer
CREATE TABLE IF NOT EXISTS public."benutzer" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "vorname" text NOT NULL,
  "nachname" text NOT NULL,
  "email" text NOT NULL,
  "passwort_hash" text NOT NULL,
  "telefonnummer" text,
  "rolle" rolle_typ DEFAULT 'kunde'::rolle_typ NOT NULL,
  "email_bestaetigt" boolean DEFAULT false NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL,
  "firma" text,
  "stripe_customer_id" text
);

-- table benutzer_adressen
CREATE TABLE IF NOT EXISTS public."benutzer_adressen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "benutzer_id" uuid NOT NULL,
  "bezeichnung" text,
  "strasse" text NOT NULL,
  "plz" text NOT NULL,
  "ort" text NOT NULL,
  "bundesland" text,
  "land" text DEFAULT 'DE'::text NOT NULL,
  "standard_lieferadresse" boolean DEFAULT false NOT NULL,
  "standard_rechnungsadresse" boolean DEFAULT false NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table bestellpositionen
CREATE TABLE IF NOT EXISTS public."bestellpositionen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "bestellung_id" uuid NOT NULL,
  "artikel_id" uuid,
  "buchung_id" uuid,
  "typ" text NOT NULL,
  "titel" text NOT NULL,
  "artikelnummer" text,
  "menge" integer DEFAULT 1 NOT NULL,
  "preis_brutto" numeric(10,2) NOT NULL,
  "steuersatz" numeric(4,2) NOT NULL,
  "variante_name" text,
  "einzelpreis_netto" numeric(10,2) DEFAULT 0,
  "erstellt_am" timestamp with time zone DEFAULT now()
);

-- table bestellungen
CREATE TABLE IF NOT EXISTS public."bestellungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "bestellnummer" text NOT NULL,
  "benutzer_id" uuid,
  "status" bestell_status DEFAULT 'offen'::bestell_status NOT NULL,
  "zwischensumme_brutto" numeric(10,2) NOT NULL,
  "steuer_summe" numeric(10,2) NOT NULL,
  "versand_brutto" numeric(10,2) DEFAULT 0 NOT NULL,
  "gesamt_brutto" numeric(10,2) NOT NULL,
  "rechnungsadresse_json" jsonb NOT NULL,
  "lieferadresse_json" jsonb,
  "bestellt_am" timestamp with time zone,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL,
  "notizen" jsonb DEFAULT '[]'::jsonb,
  "gast_email" text,
  "zahlungsmethode" text,
  "stripe_session_id" text,
  "stripe_payment_intent_id" text,
  "stripe_customer_id" text
);

-- table buchung_dienstleistungen
CREATE TABLE IF NOT EXISTS public."buchung_dienstleistungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "buchung_id" uuid NOT NULL,
  "dienstleistung_id" uuid NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table buchungen
CREATE TABLE IF NOT EXISTS public."buchungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "benutzer_id" uuid,
  "dienstleistung_id" uuid NOT NULL,
  "techniker_id" uuid,
  "adresse_id" uuid,
  "geplant_von" timestamp with time zone NOT NULL,
  "geplant_bis" timestamp with time zone NOT NULL,
  "status" buchung_status DEFAULT 'ausstehend'::buchung_status NOT NULL,
  "hinweise" text,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL,
  "erinnerung_gesendet" boolean DEFAULT false NOT NULL,
  "kontakt_name" text,
  "kontakt_email" text,
  "kontakt_telefon" text
);

-- table dienstleistungen
CREATE TABLE IF NOT EXISTS public."dienstleistungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "code" text NOT NULL,
  "name" text NOT NULL,
  "beschreibung" text,
  "basispreis_brutto" numeric(10,2) NOT NULL,
  "steuersatz" numeric(4,2) DEFAULT 19.00 NOT NULL,
  "dauer_minuten" integer NOT NULL,
  "aktiv" boolean DEFAULT true NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now(),
  "aktualisiert_am" timestamp with time zone DEFAULT now()
);

-- table einwilligungen
CREATE TABLE IF NOT EXISTS public."einwilligungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "benutzer_id" uuid,
  "typ" text NOT NULL,
  "version" text NOT NULL,
  "angenommen_am" timestamp with time zone NOT NULL,
  "ip_adresse" text
);

-- table email_vorlagen
CREATE TABLE IF NOT EXISTS public."email_vorlagen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "typ" text NOT NULL,
  "betreff" text NOT NULL,
  "inhalt_html" text NOT NULL,
  "variablen" text[],
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table firmeneinstellungen
CREATE TABLE IF NOT EXISTS public."firmeneinstellungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "firmenname" text NOT NULL,
  "email" text NOT NULL,
  "telefon" text,
  "ust_id" text,
  "adresse_json" jsonb,
  "support_zeiten" text,
  "logo_datei_id" uuid,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL,
  "oeffnungszeiten" jsonb DEFAULT '[{"bis": "18:00", "tag": "Montag", "von": "08:00", "geoeffnet": true}, {"bis": "18:00", "tag": "Dienstag", "von": "08:00", "geoeffnet": true}, {"bis": "18:00", "tag": "Mittwoch", "von": "08:00", "geoeffnet": true}, {"bis": "18:00", "tag": "Donnerstag", "von": "08:00", "geoeffnet": true}, {"bis": "18:00", "tag": "Freitag", "von": "08:00", "geoeffnet": true}, {"bis": "14:00", "tag": "Samstag", "von": "09:00", "geoeffnet": true}, {"bis": "", "tag": "Sonntag", "von": "", "geoeffnet": false}]'::jsonb,
  "primaerfarbe" text DEFAULT '#2563EB'::text,
  "sekundaerfarbe" text DEFAULT '#0F172A'::text,
  "akzentfarbe" text DEFAULT '#3B82F6'::text,
  "support_email" text,
  "support_telefon" text,
  "versandkosten" numeric(10,2) DEFAULT 5.00,
  "versandkostenlos_ab" numeric(10,2) DEFAULT 500.00
);

-- table gesperrte_tage
CREATE TABLE IF NOT EXISTS public."gesperrte_tage" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "datum" date NOT NULL,
  "grund" text,
  "techniker_id" uuid,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table inhalt_versionen
CREATE TABLE IF NOT EXISTS public."inhalt_versionen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "rechtstext_id" uuid NOT NULL,
  "content_html" text NOT NULL,
  "version_nummer" integer NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "erstellt_von" uuid
);

-- table kategorien
CREATE TABLE IF NOT EXISTS public."kategorien" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "parent_id" uuid,
  "beschreibung" text,
  "bild_url" text,
  "anzeige_reihenfolge" integer DEFAULT 0,
  "aktiv" boolean DEFAULT true,
  "erstellt_am" timestamp with time zone DEFAULT now(),
  "aktualisiert_am" timestamp with time zone DEFAULT now()
);

-- table lagerbestaende
CREATE TABLE IF NOT EXISTS public."lagerbestaende" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "artikel_id" uuid NOT NULL,
  "bestand" integer DEFAULT 0 NOT NULL,
  "mindestbestand" integer DEFAULT 2,
  "erstellt_am" timestamp with time zone DEFAULT now(),
  "aktualisiert_am" timestamp with time zone DEFAULT now()
);

-- table marken
CREATE TABLE IF NOT EXISTS public."marken" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now()
);

-- table medien_dateien
CREATE TABLE IF NOT EXISTS public."medien_dateien" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "speicherpfad" text NOT NULL,
  "mime_type" text NOT NULL,
  "breite" integer,
  "hoehe" integer,
  "groesse_bytes" integer,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "dateiname" text,
  "bucket" text DEFAULT 'product-images'::text,
  "hochgeladen_von" uuid
);

-- table rechtstexte
CREATE TABLE IF NOT EXISTS public."rechtstexte" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "slug" text NOT NULL,
  "titel" text NOT NULL,
  "content_html" text NOT NULL,
  "version" text,
  "veröffentlicht" boolean DEFAULT true NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table techniker
CREATE TABLE IF NOT EXISTS public."techniker" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "vorname" text NOT NULL,
  "nachname" text NOT NULL,
  "telefon" text,
  "email" text,
  "aktiv" boolean DEFAULT true NOT NULL,
  "erstellt_am" timestamp with time zone DEFAULT now(),
  "aktualisiert_am" timestamp with time zone DEFAULT now()
);

-- table techniker_verfuegbarkeit
CREATE TABLE IF NOT EXISTS public."techniker_verfuegbarkeit" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "techniker_id" uuid NOT NULL,
  "wochentag" integer,
  "datum" date,
  "start_zeit" time without time zone NOT NULL,
  "ende_zeit" time without time zone NOT NULL,
  "verfuegbar" boolean DEFAULT true NOT NULL
);

-- table zahlungen
CREATE TABLE IF NOT EXISTS public."zahlungen" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "bestellung_id" uuid,
  "buchung_id" uuid,
  "anbieter" zahlungsanbieter DEFAULT 'stripe'::zahlungsanbieter NOT NULL,
  "status" zahlungs_status NOT NULL,
  "betrag_brutto" numeric(10,2) NOT NULL,
  "waehrung" text DEFAULT 'EUR'::text NOT NULL,
  "stripe_payment_intent_id" text,
  "stripe_latest_charge_id" text,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL,
  "aktualisiert_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- table zahlungsvorgaenge
CREATE TABLE IF NOT EXISTS public."zahlungsvorgaenge" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "zahlung_id" uuid NOT NULL,
  "ereignis" text NOT NULL,
  "betrag_brutto" numeric(10,2),
  "rohdaten" jsonb,
  "erstellt_am" timestamp with time zone DEFAULT now() NOT NULL
);

-- constraint benutzer_adressen_pkey
ALTER TABLE public."benutzer_adressen" ADD CONSTRAINT "benutzer_adressen_pkey" PRIMARY KEY (id);

-- constraint benutzer_email_key
ALTER TABLE public."benutzer" ADD CONSTRAINT "benutzer_email_key" UNIQUE (email);

-- constraint benutzer_pkey
ALTER TABLE public."benutzer" ADD CONSTRAINT "benutzer_pkey" PRIMARY KEY (id);

-- constraint einwilligungen_pkey
ALTER TABLE public."einwilligungen" ADD CONSTRAINT "einwilligungen_pkey" PRIMARY KEY (id);

-- constraint lagerbestaende_artikel_id_key
ALTER TABLE public."lagerbestaende" ADD CONSTRAINT "lagerbestaende_artikel_id_key" UNIQUE (artikel_id);

-- constraint lagerbestaende_pkey
ALTER TABLE public."lagerbestaende" ADD CONSTRAINT "lagerbestaende_pkey" PRIMARY KEY (id);

-- constraint artikel_artikelnummer_key
ALTER TABLE public."artikel" ADD CONSTRAINT "artikel_artikelnummer_key" UNIQUE (artikelnummer);

-- constraint artikel_pkey
ALTER TABLE public."artikel" ADD CONSTRAINT "artikel_pkey" PRIMARY KEY (id);

-- constraint artikel_slug_key
ALTER TABLE public."artikel" ADD CONSTRAINT "artikel_slug_key" UNIQUE (slug);

-- constraint artikel_technische_daten_pkey
ALTER TABLE public."artikel_technische_daten" ADD CONSTRAINT "artikel_technische_daten_pkey" PRIMARY KEY (id);

-- constraint artikel_bilder_pkey
ALTER TABLE public."artikel_bilder" ADD CONSTRAINT "artikel_bilder_pkey" PRIMARY KEY (id);

-- constraint marken_name_key
ALTER TABLE public."marken" ADD CONSTRAINT "marken_name_key" UNIQUE (name);

-- constraint marken_pkey
ALTER TABLE public."marken" ADD CONSTRAINT "marken_pkey" PRIMARY KEY (id);

-- constraint techniker_pkey
ALTER TABLE public."techniker" ADD CONSTRAINT "techniker_pkey" PRIMARY KEY (id);

-- constraint techniker_verfuegbarkeit_pkey
ALTER TABLE public."techniker_verfuegbarkeit" ADD CONSTRAINT "techniker_verfuegbarkeit_pkey" PRIMARY KEY (id);

-- constraint buchungen_pkey
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_pkey" PRIMARY KEY (id);

-- constraint buchungen_techniker_id_geplant_von_key
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_techniker_id_geplant_von_key" UNIQUE (techniker_id, geplant_von);

-- constraint dienstleistungen_code_key
ALTER TABLE public."dienstleistungen" ADD CONSTRAINT "dienstleistungen_code_key" UNIQUE (code);

-- constraint dienstleistungen_pkey
ALTER TABLE public."dienstleistungen" ADD CONSTRAINT "dienstleistungen_pkey" PRIMARY KEY (id);

-- constraint bestellungen_bestellnummer_key
ALTER TABLE public."bestellungen" ADD CONSTRAINT "bestellungen_bestellnummer_key" UNIQUE (bestellnummer);

-- constraint bestellungen_pkey
ALTER TABLE public."bestellungen" ADD CONSTRAINT "bestellungen_pkey" PRIMARY KEY (id);

-- constraint bestellpositionen_pkey
ALTER TABLE public."bestellpositionen" ADD CONSTRAINT "bestellpositionen_pkey" PRIMARY KEY (id);

-- constraint zahlungen_pkey
ALTER TABLE public."zahlungen" ADD CONSTRAINT "zahlungen_pkey" PRIMARY KEY (id);

-- constraint zahlungsvorgaenge_pkey
ALTER TABLE public."zahlungsvorgaenge" ADD CONSTRAINT "zahlungsvorgaenge_pkey" PRIMARY KEY (id);

-- constraint rechtstexte_pkey
ALTER TABLE public."rechtstexte" ADD CONSTRAINT "rechtstexte_pkey" PRIMARY KEY (id);

-- constraint rechtstexte_slug_key
ALTER TABLE public."rechtstexte" ADD CONSTRAINT "rechtstexte_slug_key" UNIQUE (slug);

-- constraint admin_audit_logs_pkey
ALTER TABLE public."admin_audit_logs" ADD CONSTRAINT "admin_audit_logs_pkey" PRIMARY KEY (id);

-- constraint firmeneinstellungen_pkey
ALTER TABLE public."firmeneinstellungen" ADD CONSTRAINT "firmeneinstellungen_pkey" PRIMARY KEY (id);

-- constraint inhalt_versionen_pkey
ALTER TABLE public."inhalt_versionen" ADD CONSTRAINT "inhalt_versionen_pkey" PRIMARY KEY (id);

-- constraint inhalt_versionen_rechtstext_id_version_nummer_key
ALTER TABLE public."inhalt_versionen" ADD CONSTRAINT "inhalt_versionen_rechtstext_id_version_nummer_key" UNIQUE (rechtstext_id, version_nummer);

-- constraint gesperrte_tage_datum_techniker_id_key
ALTER TABLE public."gesperrte_tage" ADD CONSTRAINT "gesperrte_tage_datum_techniker_id_key" UNIQUE (datum, techniker_id);

-- constraint gesperrte_tage_pkey
ALTER TABLE public."gesperrte_tage" ADD CONSTRAINT "gesperrte_tage_pkey" PRIMARY KEY (id);

-- constraint email_vorlagen_pkey
ALTER TABLE public."email_vorlagen" ADD CONSTRAINT "email_vorlagen_pkey" PRIMARY KEY (id);

-- constraint email_vorlagen_typ_key
ALTER TABLE public."email_vorlagen" ADD CONSTRAINT "email_vorlagen_typ_key" UNIQUE (typ);

-- constraint buchung_dienstleistungen_buchung_id_dienstleistung_id_key
ALTER TABLE public."buchung_dienstleistungen" ADD CONSTRAINT "buchung_dienstleistungen_buchung_id_dienstleistung_id_key" UNIQUE (buchung_id, dienstleistung_id);

-- constraint buchung_dienstleistungen_pkey
ALTER TABLE public."buchung_dienstleistungen" ADD CONSTRAINT "buchung_dienstleistungen_pkey" PRIMARY KEY (id);

-- constraint kategorien_pkey
ALTER TABLE public."kategorien" ADD CONSTRAINT "kategorien_pkey" PRIMARY KEY (id);

-- constraint kategorien_slug_key
ALTER TABLE public."kategorien" ADD CONSTRAINT "kategorien_slug_key" UNIQUE (slug);

-- constraint medien_dateien_pkey
ALTER TABLE public."medien_dateien" ADD CONSTRAINT "medien_dateien_pkey" PRIMARY KEY (id);

-- constraint benutzer_adressen_benutzer_id_fkey
ALTER TABLE public."benutzer_adressen" ADD CONSTRAINT "benutzer_adressen_benutzer_id_fkey" FOREIGN KEY (benutzer_id) REFERENCES benutzer(id) ON DELETE CASCADE;

-- constraint einwilligungen_benutzer_id_fkey
ALTER TABLE public."einwilligungen" ADD CONSTRAINT "einwilligungen_benutzer_id_fkey" FOREIGN KEY (benutzer_id) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint lagerbestaende_artikel_id_fkey
ALTER TABLE public."lagerbestaende" ADD CONSTRAINT "lagerbestaende_artikel_id_fkey" FOREIGN KEY (artikel_id) REFERENCES artikel(id) ON DELETE CASCADE;

-- constraint artikel_kategorie_id_fkey
ALTER TABLE public."artikel" ADD CONSTRAINT "artikel_kategorie_id_fkey" FOREIGN KEY (kategorie_id) REFERENCES kategorien(id);

-- constraint artikel_marke_id_fkey
ALTER TABLE public."artikel" ADD CONSTRAINT "artikel_marke_id_fkey" FOREIGN KEY (marke_id) REFERENCES marken(id);

-- constraint artikel_technische_daten_artikel_id_fkey
ALTER TABLE public."artikel_technische_daten" ADD CONSTRAINT "artikel_technische_daten_artikel_id_fkey" FOREIGN KEY (artikel_id) REFERENCES artikel(id) ON DELETE CASCADE;

-- constraint artikel_bilder_artikel_id_fkey
ALTER TABLE public."artikel_bilder" ADD CONSTRAINT "artikel_bilder_artikel_id_fkey" FOREIGN KEY (artikel_id) REFERENCES artikel(id) ON DELETE CASCADE;

-- constraint artikel_bilder_datei_id_fkey
ALTER TABLE public."artikel_bilder" ADD CONSTRAINT "artikel_bilder_datei_id_fkey" FOREIGN KEY (datei_id) REFERENCES medien_dateien(id) ON DELETE SET NULL;

-- constraint techniker_verfuegbarkeit_techniker_id_fkey
ALTER TABLE public."techniker_verfuegbarkeit" ADD CONSTRAINT "techniker_verfuegbarkeit_techniker_id_fkey" FOREIGN KEY (techniker_id) REFERENCES techniker(id) ON DELETE CASCADE;

-- constraint buchungen_adresse_id_fkey
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_adresse_id_fkey" FOREIGN KEY (adresse_id) REFERENCES benutzer_adressen(id);

-- constraint buchungen_benutzer_id_fkey
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_benutzer_id_fkey" FOREIGN KEY (benutzer_id) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint buchungen_dienstleistung_id_fkey
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_dienstleistung_id_fkey" FOREIGN KEY (dienstleistung_id) REFERENCES dienstleistungen(id) ON DELETE RESTRICT;

-- constraint buchungen_techniker_id_fkey
ALTER TABLE public."buchungen" ADD CONSTRAINT "buchungen_techniker_id_fkey" FOREIGN KEY (techniker_id) REFERENCES techniker(id);

-- constraint bestellungen_benutzer_id_fkey
ALTER TABLE public."bestellungen" ADD CONSTRAINT "bestellungen_benutzer_id_fkey" FOREIGN KEY (benutzer_id) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint bestellpositionen_artikel_id_fkey
ALTER TABLE public."bestellpositionen" ADD CONSTRAINT "bestellpositionen_artikel_id_fkey" FOREIGN KEY (artikel_id) REFERENCES artikel(id);

-- constraint bestellpositionen_bestellung_id_fkey
ALTER TABLE public."bestellpositionen" ADD CONSTRAINT "bestellpositionen_bestellung_id_fkey" FOREIGN KEY (bestellung_id) REFERENCES bestellungen(id) ON DELETE CASCADE;

-- constraint bestellpositionen_buchung_id_fkey
ALTER TABLE public."bestellpositionen" ADD CONSTRAINT "bestellpositionen_buchung_id_fkey" FOREIGN KEY (buchung_id) REFERENCES buchungen(id);

-- constraint zahlungen_bestellung_id_fkey
ALTER TABLE public."zahlungen" ADD CONSTRAINT "zahlungen_bestellung_id_fkey" FOREIGN KEY (bestellung_id) REFERENCES bestellungen(id);

-- constraint zahlungen_buchung_id_fkey
ALTER TABLE public."zahlungen" ADD CONSTRAINT "zahlungen_buchung_id_fkey" FOREIGN KEY (buchung_id) REFERENCES buchungen(id);

-- constraint zahlungsvorgaenge_zahlung_id_fkey
ALTER TABLE public."zahlungsvorgaenge" ADD CONSTRAINT "zahlungsvorgaenge_zahlung_id_fkey" FOREIGN KEY (zahlung_id) REFERENCES zahlungen(id) ON DELETE CASCADE;

-- constraint admin_audit_logs_actor_benutzer_id_fkey
ALTER TABLE public."admin_audit_logs" ADD CONSTRAINT "admin_audit_logs_actor_benutzer_id_fkey" FOREIGN KEY (actor_benutzer_id) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint admin_audit_logs_admin_id_fkey
ALTER TABLE public."admin_audit_logs" ADD CONSTRAINT "admin_audit_logs_admin_id_fkey" FOREIGN KEY (admin_id) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint inhalt_versionen_erstellt_von_fkey
ALTER TABLE public."inhalt_versionen" ADD CONSTRAINT "inhalt_versionen_erstellt_von_fkey" FOREIGN KEY (erstellt_von) REFERENCES benutzer(id) ON DELETE SET NULL;

-- constraint inhalt_versionen_rechtstext_id_fkey
ALTER TABLE public."inhalt_versionen" ADD CONSTRAINT "inhalt_versionen_rechtstext_id_fkey" FOREIGN KEY (rechtstext_id) REFERENCES rechtstexte(id) ON DELETE CASCADE;

-- constraint gesperrte_tage_techniker_id_fkey
ALTER TABLE public."gesperrte_tage" ADD CONSTRAINT "gesperrte_tage_techniker_id_fkey" FOREIGN KEY (techniker_id) REFERENCES techniker(id) ON DELETE CASCADE;

-- constraint buchung_dienstleistungen_buchung_id_fkey
ALTER TABLE public."buchung_dienstleistungen" ADD CONSTRAINT "buchung_dienstleistungen_buchung_id_fkey" FOREIGN KEY (buchung_id) REFERENCES buchungen(id) ON DELETE CASCADE;

-- constraint buchung_dienstleistungen_dienstleistung_id_fkey
ALTER TABLE public."buchung_dienstleistungen" ADD CONSTRAINT "buchung_dienstleistungen_dienstleistung_id_fkey" FOREIGN KEY (dienstleistung_id) REFERENCES dienstleistungen(id) ON DELETE CASCADE;

-- constraint kategorien_parent_id_fkey
ALTER TABLE public."kategorien" ADD CONSTRAINT "kategorien_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES kategorien(id);

-- constraint medien_dateien_hochgeladen_von_fkey
ALTER TABLE public."medien_dateien" ADD CONSTRAINT "medien_dateien_hochgeladen_von_fkey" FOREIGN KEY (hochgeladen_von) REFERENCES benutzer(id) ON DELETE SET NULL;

-- index idx_benutzer_stripe_customer_id
CREATE INDEX idx_benutzer_stripe_customer_id ON public.benutzer USING btree (stripe_customer_id) WHERE (stripe_customer_id IS NOT NULL);

-- index idx_artikel_kategorie
CREATE INDEX idx_artikel_kategorie ON public.artikel USING btree (kategorie_id);

-- index idx_artikel_marke
CREATE INDEX idx_artikel_marke ON public.artikel USING btree (marke_id);

-- index idx_techniker_zeit
CREATE INDEX idx_techniker_zeit ON public.buchungen USING btree (techniker_id, geplant_von);

-- index idx_buchungen_benutzer
CREATE INDEX idx_buchungen_benutzer ON public.buchungen USING btree (benutzer_id);

-- index idx_buchungen_kontakt_email
CREATE INDEX idx_buchungen_kontakt_email ON public.buchungen USING btree (kontakt_email);

-- index idx_buchungen_benutzer_id
CREATE INDEX idx_buchungen_benutzer_id ON public.buchungen USING btree (benutzer_id);

-- index idx_bestellungen_stripe_customer_id
CREATE INDEX idx_bestellungen_stripe_customer_id ON public.bestellungen USING btree (stripe_customer_id) WHERE (stripe_customer_id IS NOT NULL);

-- index idx_bestellpositionen_bestellung
CREATE INDEX idx_bestellpositionen_bestellung ON public.bestellpositionen USING btree (bestellung_id);

-- index idx_audit_entitaet_typ
CREATE INDEX idx_audit_entitaet_typ ON public.admin_audit_logs USING btree (entitaet_typ);

-- index idx_audit_erstellt
CREATE INDEX idx_audit_erstellt ON public.admin_audit_logs USING btree (erstellt_am DESC);

-- index single_firmeneinstellungen
CREATE UNIQUE INDEX single_firmeneinstellungen ON public.firmeneinstellungen USING btree ((true));

-- index idx_inhalt_versionen_rechtstext
CREATE INDEX idx_inhalt_versionen_rechtstext ON public.inhalt_versionen USING btree (rechtstext_id);

-- index idx_buchung_dl_buchung
CREATE INDEX idx_buchung_dl_buchung ON public.buchung_dienstleistungen USING btree (buchung_id);

-- function update_aktualisiert_am
CREATE OR REPLACE FUNCTION public.update_aktualisiert_am()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.aktualisiert_am = now();
  RETURN NEW;
END;
$function$
;

-- function handle_user_updated
CREATE OR REPLACE FUNCTION public.handle_user_updated()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF NEW.email_confirmed_at IS NOT NULL AND OLD.email_confirmed_at IS NULL THEN
    UPDATE public.benutzer
    SET    email_bestaetigt = true,
           aktualisiert_am  = now()
    WHERE  id = NEW.id;
  END IF;
  RETURN NEW;
END;
$function$
;

-- function handle_new_user
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.benutzer (
    id, vorname, nachname, email, passwort_hash,
    telefonnummer, firma, rolle, email_bestaetigt
  ) VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'vorname', ''), ''),
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'nachname', ''), ''),
    NEW.email,
    'supabase-auth',
    NULLIF(NEW.raw_user_meta_data->>'telefon', ''),
    NULLIF(NEW.raw_user_meta_data->>'firma',   ''),
    'kunde',
    CASE WHEN NEW.email_confirmed_at IS NOT NULL THEN true ELSE false END
  );
  RETURN NEW;

EXCEPTION WHEN unique_violation THEN
  -- Email already exists from a previous (possibly deleted) auth user.
  -- Remove the stale orphaned row (different id, same email) then re-insert.
  DELETE FROM public.benutzer WHERE email = NEW.email AND id != NEW.id;

  INSERT INTO public.benutzer (
    id, vorname, nachname, email, passwort_hash,
    telefonnummer, firma, rolle, email_bestaetigt
  ) VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'vorname', ''), ''),
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'nachname', ''), ''),
    NEW.email,
    'supabase-auth',
    NULLIF(NEW.raw_user_meta_data->>'telefon', ''),
    NULLIF(NEW.raw_user_meta_data->>'firma',   ''),
    'kunde',
    CASE WHEN NEW.email_confirmed_at IS NOT NULL THEN true ELSE false END
  )
  ON CONFLICT (id) DO UPDATE SET
    vorname          = EXCLUDED.vorname,
    nachname         = EXCLUDED.nachname,
    telefonnummer    = EXCLUDED.telefonnummer,
    firma            = EXCLUDED.firma,
    email_bestaetigt = EXCLUDED.email_bestaetigt,
    aktualisiert_am  = now();

  RETURN NEW;
END;
$function$
;

-- trigger set_aktualisiert_email_vorlagen
DROP TRIGGER IF EXISTS "set_aktualisiert_email_vorlagen" ON "public"."email_vorlagen"; CREATE TRIGGER set_aktualisiert_email_vorlagen BEFORE UPDATE ON public.email_vorlagen FOR EACH ROW EXECUTE FUNCTION update_aktualisiert_am();

-- trigger on_auth_user_created
DROP TRIGGER IF EXISTS "on_auth_user_created" ON "auth"."users"; CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- trigger set_aktualisiert_lagerbestaende
DROP TRIGGER IF EXISTS "set_aktualisiert_lagerbestaende" ON "public"."lagerbestaende"; CREATE TRIGGER set_aktualisiert_lagerbestaende BEFORE UPDATE ON public.lagerbestaende FOR EACH ROW EXECUTE FUNCTION update_aktualisiert_am();

-- trigger set_aktualisiert_kategorien
DROP TRIGGER IF EXISTS "set_aktualisiert_kategorien" ON "public"."kategorien"; CREATE TRIGGER set_aktualisiert_kategorien BEFORE UPDATE ON public.kategorien FOR EACH ROW EXECUTE FUNCTION update_aktualisiert_am();

-- trigger set_aktualisiert_dienstleistungen
DROP TRIGGER IF EXISTS "set_aktualisiert_dienstleistungen" ON "public"."dienstleistungen"; CREATE TRIGGER set_aktualisiert_dienstleistungen BEFORE UPDATE ON public.dienstleistungen FOR EACH ROW EXECUTE FUNCTION update_aktualisiert_am();

-- trigger set_aktualisiert_techniker
DROP TRIGGER IF EXISTS "set_aktualisiert_techniker" ON "public"."techniker"; CREATE TRIGGER set_aktualisiert_techniker BEFORE UPDATE ON public.techniker FOR EACH ROW EXECUTE FUNCTION update_aktualisiert_am();

-- trigger on_auth_user_updated
DROP TRIGGER IF EXISTS "on_auth_user_updated" ON "auth"."users"; CREATE TRIGGER on_auth_user_updated AFTER UPDATE ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_user_updated();

-- rls benutzer_adressen
ALTER TABLE public."benutzer_adressen" ENABLE ROW LEVEL SECURITY;

-- rls benutzer
ALTER TABLE public."benutzer" ENABLE ROW LEVEL SECURITY;

-- rls einwilligungen
ALTER TABLE public."einwilligungen" ENABLE ROW LEVEL SECURITY;

-- rls lagerbestaende
ALTER TABLE public."lagerbestaende" ENABLE ROW LEVEL SECURITY;

-- rls artikel
ALTER TABLE public."artikel" ENABLE ROW LEVEL SECURITY;

-- rls artikel_technische_daten
ALTER TABLE public."artikel_technische_daten" ENABLE ROW LEVEL SECURITY;

-- rls artikel_bilder
ALTER TABLE public."artikel_bilder" ENABLE ROW LEVEL SECURITY;

-- rls marken
ALTER TABLE public."marken" ENABLE ROW LEVEL SECURITY;

-- rls techniker
ALTER TABLE public."techniker" ENABLE ROW LEVEL SECURITY;

-- rls techniker_verfuegbarkeit
ALTER TABLE public."techniker_verfuegbarkeit" ENABLE ROW LEVEL SECURITY;

-- rls buchungen
ALTER TABLE public."buchungen" ENABLE ROW LEVEL SECURITY;

-- rls dienstleistungen
ALTER TABLE public."dienstleistungen" ENABLE ROW LEVEL SECURITY;

-- rls bestellungen
ALTER TABLE public."bestellungen" ENABLE ROW LEVEL SECURITY;

-- rls bestellpositionen
ALTER TABLE public."bestellpositionen" ENABLE ROW LEVEL SECURITY;

-- rls zahlungen
ALTER TABLE public."zahlungen" ENABLE ROW LEVEL SECURITY;

-- rls zahlungsvorgaenge
ALTER TABLE public."zahlungsvorgaenge" ENABLE ROW LEVEL SECURITY;

-- rls rechtstexte
ALTER TABLE public."rechtstexte" ENABLE ROW LEVEL SECURITY;

-- rls admin_audit_logs
ALTER TABLE public."admin_audit_logs" ENABLE ROW LEVEL SECURITY;

-- rls firmeneinstellungen
ALTER TABLE public."firmeneinstellungen" ENABLE ROW LEVEL SECURITY;

-- rls inhalt_versionen
ALTER TABLE public."inhalt_versionen" ENABLE ROW LEVEL SECURITY;

-- rls gesperrte_tage
ALTER TABLE public."gesperrte_tage" ENABLE ROW LEVEL SECURITY;

-- rls email_vorlagen
ALTER TABLE public."email_vorlagen" ENABLE ROW LEVEL SECURITY;

-- rls buchung_dienstleistungen
ALTER TABLE public."buchung_dienstleistungen" ENABLE ROW LEVEL SECURITY;

-- rls kategorien
ALTER TABLE public."kategorien" ENABLE ROW LEVEL SECURITY;

-- rls medien_dateien
ALTER TABLE public."medien_dateien" ENABLE ROW LEVEL SECURITY;

-- policy customer_adressen_delete
DROP POLICY IF EXISTS "customer_adressen_delete" ON public."benutzer_adressen";
CREATE POLICY "customer_adressen_delete" ON public."benutzer_adressen" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = benutzer_id));

-- policy customer_adressen_insert
DROP POLICY IF EXISTS "customer_adressen_insert" ON public."benutzer_adressen";
CREATE POLICY "customer_adressen_insert" ON public."benutzer_adressen" AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = benutzer_id));

-- policy customer_adressen_select
DROP POLICY IF EXISTS "customer_adressen_select" ON public."benutzer_adressen";
CREATE POLICY "customer_adressen_select" ON public."benutzer_adressen" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = benutzer_id));

-- policy customer_adressen_update
DROP POLICY IF EXISTS "customer_adressen_update" ON public."benutzer_adressen";
CREATE POLICY "customer_adressen_update" ON public."benutzer_adressen" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = benutzer_id)) WITH CHECK ((auth.uid() = benutzer_id));

-- policy Benutzer kann eigenes Konto löschen
DROP POLICY IF EXISTS "Benutzer kann eigenes Konto löschen" ON public."benutzer";
CREATE POLICY "Benutzer kann eigenes Konto löschen" ON public."benutzer" AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = id));

-- policy customer_benutzer_select
DROP POLICY IF EXISTS "customer_benutzer_select" ON public."benutzer";
CREATE POLICY "customer_benutzer_select" ON public."benutzer" AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id));

-- policy customer_benutzer_update
DROP POLICY IF EXISTS "customer_benutzer_update" ON public."benutzer";
CREATE POLICY "customer_benutzer_update" ON public."benutzer" AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));

-- policy system_benutzer_insert
DROP POLICY IF EXISTS "system_benutzer_insert" ON public."benutzer";
CREATE POLICY "system_benutzer_insert" ON public."benutzer" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- policy public_lagerbestaende_select
DROP POLICY IF EXISTS "public_lagerbestaende_select" ON public."lagerbestaende";
CREATE POLICY "public_lagerbestaende_select" ON public."lagerbestaende" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_artikel_select
DROP POLICY IF EXISTS "public_artikel_select" ON public."artikel";
CREATE POLICY "public_artikel_select" ON public."artikel" AS PERMISSIVE FOR SELECT TO public USING ((aktiv = true));

-- policy public_artikel_technische_daten_select
DROP POLICY IF EXISTS "public_artikel_technische_daten_select" ON public."artikel_technische_daten";
CREATE POLICY "public_artikel_technische_daten_select" ON public."artikel_technische_daten" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_artikel_bilder_select
DROP POLICY IF EXISTS "public_artikel_bilder_select" ON public."artikel_bilder";
CREATE POLICY "public_artikel_bilder_select" ON public."artikel_bilder" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_marken_select
DROP POLICY IF EXISTS "public_marken_select" ON public."marken";
CREATE POLICY "public_marken_select" ON public."marken" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_techniker_select
DROP POLICY IF EXISTS "public_techniker_select" ON public."techniker";
CREATE POLICY "public_techniker_select" ON public."techniker" AS PERMISSIVE FOR SELECT TO public USING ((aktiv = true));

-- policy Oeffentlich: Techniker Verfuegbarkeit lesen
DROP POLICY IF EXISTS "Oeffentlich: Techniker Verfuegbarkeit lesen" ON public."techniker_verfuegbarkeit";
CREATE POLICY "Oeffentlich: Techniker Verfuegbarkeit lesen" ON public."techniker_verfuegbarkeit" AS PERMISSIVE FOR SELECT TO public USING ((verfuegbar = true));

-- policy public_techniker_verfuegbarkeit_select
DROP POLICY IF EXISTS "public_techniker_verfuegbarkeit_select" ON public."techniker_verfuegbarkeit";
CREATE POLICY "public_techniker_verfuegbarkeit_select" ON public."techniker_verfuegbarkeit" AS PERMISSIVE FOR SELECT TO public USING ((verfuegbar = true));

-- policy customer_buchungen_select
DROP POLICY IF EXISTS "customer_buchungen_select" ON public."buchungen";
CREATE POLICY "customer_buchungen_select" ON public."buchungen" AS PERMISSIVE FOR SELECT TO public USING (((benutzer_id IS NOT NULL) AND (auth.uid() = benutzer_id)));

-- policy public_buchungen_insert
DROP POLICY IF EXISTS "public_buchungen_insert" ON public."buchungen";
CREATE POLICY "public_buchungen_insert" ON public."buchungen" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- policy public_dienstleistungen_select
DROP POLICY IF EXISTS "public_dienstleistungen_select" ON public."dienstleistungen";
CREATE POLICY "public_dienstleistungen_select" ON public."dienstleistungen" AS PERMISSIVE FOR SELECT TO public USING ((aktiv = true));

-- policy customer_bestellungen_select
DROP POLICY IF EXISTS "customer_bestellungen_select" ON public."bestellungen";
CREATE POLICY "customer_bestellungen_select" ON public."bestellungen" AS PERMISSIVE FOR SELECT TO public USING (((benutzer_id IS NOT NULL) AND (auth.uid() = benutzer_id)));

-- policy public_bestellungen_insert
DROP POLICY IF EXISTS "public_bestellungen_insert" ON public."bestellungen";
CREATE POLICY "public_bestellungen_insert" ON public."bestellungen" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- policy customer_bestellpositionen_select
DROP POLICY IF EXISTS "customer_bestellpositionen_select" ON public."bestellpositionen";
CREATE POLICY "customer_bestellpositionen_select" ON public."bestellpositionen" AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM bestellungen b
  WHERE ((b.id = bestellpositionen.bestellung_id) AND (b.benutzer_id = auth.uid())))));

-- policy public_bestellpositionen_insert
DROP POLICY IF EXISTS "public_bestellpositionen_insert" ON public."bestellpositionen";
CREATE POLICY "public_bestellpositionen_insert" ON public."bestellpositionen" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- policy public_rechtstexte_select
DROP POLICY IF EXISTS "public_rechtstexte_select" ON public."rechtstexte";
CREATE POLICY "public_rechtstexte_select" ON public."rechtstexte" AS PERMISSIVE FOR SELECT TO public USING (("veröffentlicht" = true));

-- policy public_firmeneinstellungen_select
DROP POLICY IF EXISTS "public_firmeneinstellungen_select" ON public."firmeneinstellungen";
CREATE POLICY "public_firmeneinstellungen_select" ON public."firmeneinstellungen" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy auth_inhalt_versionen_select
DROP POLICY IF EXISTS "auth_inhalt_versionen_select" ON public."inhalt_versionen";
CREATE POLICY "auth_inhalt_versionen_select" ON public."inhalt_versionen" AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

-- policy Oeffentlich: Gesperrte Tage lesen
DROP POLICY IF EXISTS "Oeffentlich: Gesperrte Tage lesen" ON public."gesperrte_tage";
CREATE POLICY "Oeffentlich: Gesperrte Tage lesen" ON public."gesperrte_tage" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_gesperrte_tage_select
DROP POLICY IF EXISTS "public_gesperrte_tage_select" ON public."gesperrte_tage";
CREATE POLICY "public_gesperrte_tage_select" ON public."gesperrte_tage" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy auth_email_vorlagen_select
DROP POLICY IF EXISTS "auth_email_vorlagen_select" ON public."email_vorlagen";
CREATE POLICY "auth_email_vorlagen_select" ON public."email_vorlagen" AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));

-- policy customer_buchung_dl_select
DROP POLICY IF EXISTS "customer_buchung_dl_select" ON public."buchung_dienstleistungen";
CREATE POLICY "customer_buchung_dl_select" ON public."buchung_dienstleistungen" AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM buchungen b
  WHERE ((b.id = buchung_dienstleistungen.buchung_id) AND (b.benutzer_id = auth.uid())))));

-- policy public_buchung_dl_insert
DROP POLICY IF EXISTS "public_buchung_dl_insert" ON public."buchung_dienstleistungen";
CREATE POLICY "public_buchung_dl_insert" ON public."buchung_dienstleistungen" AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);

-- policy Oeffentlich: Kategorien lesen
DROP POLICY IF EXISTS "Oeffentlich: Kategorien lesen" ON public."kategorien";
CREATE POLICY "Oeffentlich: Kategorien lesen" ON public."kategorien" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_kategorien_select
DROP POLICY IF EXISTS "public_kategorien_select" ON public."kategorien";
CREATE POLICY "public_kategorien_select" ON public."kategorien" AS PERMISSIVE FOR SELECT TO public USING (true);

-- policy public_medien_dateien_select
DROP POLICY IF EXISTS "public_medien_dateien_select" ON public."medien_dateien";
CREATE POLICY "public_medien_dateien_select" ON public."medien_dateien" AS PERMISSIVE FOR SELECT TO public USING (true);

-- grant schema
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- grant tables
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;

-- grant sequences
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
